# Generated by Django 4.2.6 on 2023-11-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oppositons',
            fields=[
                ('op_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
