# Generated by Django 4.2.6 on 2023-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_oppositons'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('c_party', models.CharField(max_length=50, unique=True)),
                ('c_name', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
