# Generated by Django 4.2.6 on 2023-11-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oppositons',
            new_name='oppositions',
        ),
        migrations.DeleteModel(
            name='candidate',
        ),
    ]
